const actionTypes = {
    SET_HOTELS: 'SET_HOTELS',
    SET_RESTAURANTS: 'SET_RESTAURANTS',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_HARDCODED_HOTELS: 'SET_HARDCODED_HOTELS',
    SET_HARDCODED_RESTAURANTS: 'SET_HARDCODED_RESTAURANTS',
    SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
};
export default actionTypes;