const actionTypes = {
    SET_HOTELS: 'SET_HOTELS',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_HARCODED_HOTELS: 'SET_HARCODED_HOTELS',
    SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
};
export default actionTypes;